"""PDF report generator for ScholAR - Working version."""

from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_JUSTIFY, TA_CENTER
from reportlab.lib import colors
import re


def convert_markdown_to_html(text: str) -> str:
    """Convert markdown formatting to HTML tags that ReportLab understands."""
    # Replace inline **bold**
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    # Replace inline *italic* (if needed)
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    return text


def generate_pdf_from_markdown(markdown_text: str) -> bytes:
    """
    Generate a professional PDF directly from markdown text.
    Ensures ALL content is included in the PDF.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )

    story = []
    styles = getSampleStyleSheet()

    # Define custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#0066cc'),
        spaceAfter=20,
        spaceBefore=10,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )

    h2_style = ParagraphStyle(
        'CustomH2',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#003d99'),
        spaceAfter=12,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )

    h3_style = ParagraphStyle(
        'CustomH3',
        parent=styles['Heading3'],
        fontSize=13,
        textColor=colors.HexColor('#333333'),
        spaceAfter=10,
        spaceBefore=8,
        fontName='Helvetica-Bold'
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        alignment=TA_JUSTIFY,
        spaceAfter=12,
        leading=16
    )

    list_style = ParagraphStyle(
        'CustomList',
        parent=styles['BodyText'],
        fontSize=11,
        alignment=TA_LEFT,
        spaceAfter=8,
        leading=14,
        leftIndent=20
    )

    # Add title
    story.append(Paragraph("Literature Review Report", title_style))
    story.append(Paragraph("Generated by ScholAR - Autonomous Research Agent", body_style))
    story.append(Spacer(1, 0.3*inch))

    # Parse and add all content from markdown
    lines = markdown_text.split('\n')

    for line in lines:
        stripped = line.strip()

        if not stripped:
            story.append(Spacer(1, 0.1*inch))
            continue

        try:
            # H1 headings
            if stripped.startswith('# '):
                text = stripped[2:].strip()
                if text:
                    text = convert_markdown_to_html(text)
                    story.append(Paragraph(text, title_style))
                    story.append(Spacer(1, 0.15*inch))

            # H2 headings
            elif stripped.startswith('## '):
                text = stripped[3:].strip()
                if text:
                    text = convert_markdown_to_html(text)
                    story.append(Paragraph(text, h2_style))
                    story.append(Spacer(1, 0.1*inch))

            # H3 headings
            elif stripped.startswith('### '):
                text = stripped[4:].strip()
                if text:
                    text = convert_markdown_to_html(text)
                    story.append(Paragraph(text, h3_style))
                    story.append(Spacer(1, 0.05*inch))

            # Bullet points
            elif stripped.startswith('- '):
                text = stripped[2:].strip()
                if text:
                    text = convert_markdown_to_html(text)
                    story.append(Paragraph(f"• {text}", list_style))

            # Regular paragraphs (with inline markdown support)
            else:
                if len(stripped) > 0:
                    text = convert_markdown_to_html(stripped)
                    story.append(Paragraph(text, body_style))

        except Exception as e:
            # Continue with other content if one line fails
            try:
                text = convert_markdown_to_html(stripped)
                story.append(Paragraph(text, body_style))
            except:
                pass

    # Add footer
    story.append(Spacer(1, 0.3*inch))
    footer_text = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#999999'),
        alignment=TA_CENTER
    )
    story.append(Paragraph("Generated by ScholAR | Autonomous Research Discovery", footer_text))

    # Build PDF - THIS IS KEY - must call build()
    try:
        doc.build(story)
        buffer.seek(0)
        pdf_data = buffer.getvalue()

        if len(pdf_data) > 100:  # Check if PDF has content
            return pdf_data
        else:
            raise Exception("Generated PDF is too small")

    except Exception as e:
        print(f"PDF build error: {e}")
        raise


def generate_report_bytes(markdown_text: str, format_type: str = "pdf", research_data: dict = None) -> tuple:
    """
    Generate report - supports complete literature review.
    Returns: (bytes, file_extension, mime_type)
    """
    if format_type.lower() == "pdf":
        try:
            # If research_data provided, create comprehensive report
            if research_data:
                complete_markdown = build_complete_literature_review(research_data)
                pdf_bytes = generate_pdf_from_markdown(complete_markdown)
            else:
                # Fallback to markdown text only
                pdf_bytes = generate_pdf_from_markdown(markdown_text)
            return pdf_bytes, "pdf", "application/pdf"
        except Exception as e:
            print(f"PDF generation failed: {e}")
            raise
    else:
        raise ValueError("Only PDF format is supported")


def build_complete_literature_review(data: dict) -> str:
    """Build comprehensive markdown literature review from research data."""
    md = []

    # Title section
    topic = data.get('topic', 'Research Topic')
    md.append(f"# Literature Review: {topic}\n")
    md.append(f"**Generated by:** ScholAR - Autonomous Research Agent\n")
    md.append(f"**Date:** {data.get('timestamp', 'N/A')}\n\n")

    # Executive Summary
    md.append("## Executive Summary\n")
    papers_count = len(data.get('papers', []))
    contradictions_count = len(data.get('contradictions', []))
    md.append(f"This comprehensive literature review analyzes **{papers_count} peer-reviewed papers** ")
    md.append(f"on the topic of **{topic}**, identifying **{contradictions_count} key research contradictions** ")
    md.append("and synthesizing findings across the scientific literature.\n\n")

    # Main Report
    report_text = data.get('report', '')
    if report_text:
        md.append("## Research Analysis\n")
        md.append(report_text)
        md.append("\n\n")

    # Contradictions Section
    contradictions = data.get('contradictions', [])
    if contradictions:
        md.append("## 🔴 Key Contradictions in the Literature\n\n")
        themes = {}
        for contra in contradictions:
            theme = contra.get('theme', 'Other')
            themes.setdefault(theme, []).append(contra)

        for theme, items in themes.items():
            md.append(f"### {theme}\n\n")
            for idx, item in enumerate(items, 1):
                md.append(f"**Contradiction {idx}:**\n")
                md.append(f"- **Paper A:** {item.get('paper_a', 'N/A')}\n")
                md.append(f"  - **Claim:** {item.get('claim_a', 'N/A')}\n")
                md.append(f"- **Paper B:** {item.get('paper_b', 'N/A')}\n")
                md.append(f"  - **Claim:** {item.get('claim_b', 'N/A')}\n\n")

    # Papers/Sources Section
    papers = data.get('papers', [])
    if papers:
        md.append("## 📚 Papers Reviewed\n\n")
        md.append(f"A total of **{len(papers)} papers** were analyzed:\n\n")

        for idx, paper in enumerate(papers, 1):
            title = paper.get('title', 'N/A')
            authors = paper.get('authors', 'N/A')
            year = paper.get('year', 'N/A')
            abstract = paper.get('abstract', 'N/A')

            md.append(f"### {idx}. {title}\n\n")
            md.append(f"**Authors:** {authors}\n")
            md.append(f"**Year:** {year}\n")
            if abstract and abstract != 'N/A':
                md.append(f"**Abstract:** {abstract}\n")
            md.append("\n")

    # Methodology Section
    md.append("## Methodology\n\n")
    md.append("This review was conducted using the **Semantic Scholar API** to search peer-reviewed literature. ")
    md.append("The analysis employed **autonomous research agent technology** to:\n\n")
    md.append("- Identify relevant papers and key concepts\n")
    md.append("- Extract and analyze research contradictions\n")
    md.append("- Synthesize findings across multiple studies\n")
    md.append("- Generate comprehensive insights\n\n")

    # Conclusion
    md.append("## Conclusion\n\n")
    md.append(f"This systematic review of {len(papers)} papers on **{topic}** reveals ")
    md.append(f"{contradictions_count} significant contradictions in the literature. ")
    md.append("Further research is recommended to resolve these discrepancies and advance understanding of the field.\n\n")

    # Footer
    md.append("---\n")
    md.append("**Report Generated by ScholAR** | Autonomous Research Discovery Platform\n")

    return ''.join(md)

